job:
  name: latest
  max_steps: 3000
  logging: True
  debug_tls: []

sumo:
  dir: "sumo"
  gui: True
  sumocfg: run.sumocfg

tls:
  - id: B1
    controller: base_crosswalk
    constants:
      MIN_TIME: 15
    variables:
      ped_count: 0
    extract:
      - feature: count
        user_class: pedestrian
        from: phase
        mapping:
          2: ped_count

  - id: B2
    controller: base_crosswalk
    variables:
      ped_count: 0
    extract:
      - feature: count
        user_class: pedestrian
        from: phase
        mapping:
          2: ped_count

  - id: A1
    controller: base_timed

  - id: C1
    controller: stratego
    constants:
      phase_map:
        0: 0
        1: 1
        2: 2
        3: 3
      horizon: 60
      mpc_step: 5
      min_green: 4
      model_template: stratego/four_phase_template.xml
      verifyta_query: stratego/four_phase_query.q
      verifyta_command: verifyta
      debug: False
    variables:
      A: [0, 0, 0]
      B: [0, 0, 0]
      x: 0.0
      is_active: [0, 0, 0, 0]
    extract:
    - feature: count
      user_class: passenger
      from: lane
      mapping:
        C01_1: ["A", 0]
        C01_2: ["A", 1]
        C21_1: ["A", 0]
        C21_2: ["A", 1]
        BC1_1: ["B", 0]
        BC1_2: ["B", 1]
        YC1_1: ["B", 0]
        YC1_2: ["B", 1]