job:
  name: latest
  max_steps: 3000
  logging: True
  debug_tls: []

sumo:
  dir: "sumo"
  gui: True
  sumocfg: "run.sumocfg"

tls:
  - id: "B1"
    controller: base_crosswalk
    constants:
      MIN_TIME: 15
    variables:
      ped_count: 0
    extract:
      - feature: count
        user_type: pedestrian
        from: phase
        mapping:
          2: "ped_count"

  - id: "B2"
    controller: base_crosswalk
    constants:
      MIN_TIME: 10
    variables:
      ped_count: 0
    extract:
      - feature: count
        user_type: pedestrian
        from: phase
        mapping:
          2: "ped_count"
