job:
  name: latest
  max_steps: 3000
  logging: True
  debug_tls: []

sumo:
  dir: "sumo"
  gui: True
  sumocfg: run.sumocfg

tls:
  - id: B1
    controller: base_crosswalk
    constants:
      MIN_TIME: 15
    variables:
      ped_count: 0
    extract:
      - feature: count
        user_type: pedestrian
        from: phase
        mapping:
          2: ped_count

  - id: B2
    controller: base_crosswalk
    variables:
      ped_count: 0
    extract:
      - feature: count
        user_type: pedestrian
        from: phase
        mapping:
          2: ped_count

  - id: A1
    controller: base_timed
    constants: 
      network_path: sumo/block.net.xml

  - id: C1
    controller: strategonodos
    constants:
      horizon: 60
      mpc_step: 5
      min_green: 4
      model_template: README.md
      verifyta_query: README.md
      verifyta_command: README.md
      debug: False
    variables:
      no: [1, 0, 0]
      