job:
  name: cross
  dir: examples/cross

logging:
  ids: [B1, B2]
  data: [state]
  to_file: False
  to_console: True

sumo:
  dir: "sumo"
  gui: True
  max_steps: 3000
  network: networks/cross6_LFR_exits.net.xml
  additional: [networks/cross5_w_yellow.tll.xml]
  route: [demands/vehicles.rou.xml, demands/pedestrians.rou.xml, demands/cyclists.rou.xml]

tls:
  - id: C
    controller: stratego
    constants:
      n_movement_phases: 4
      horizon: 60
      mpc_step: 4
      min_green: 4
      model_template: stratego/four_phase_template.xml
      verifyta_query: stratego/four_phase_query.q
      verifyta_command: verifyta
      debug: False

    variables:
      A: [0, 0, 0]
      B: [0, 0, 0]
      CYC_A: 0
      CYC_B: 0
      PED_A: 0
      PED_B: 0
      x: 0.0
      is_active: 0

    extract:
      user_data:
      - feature: count
        user_class: passenger
        at: lane
        mapping:
          NC_4: ["A", 0]
          NC_3: ["A", 1]
          NC_2: ["A", 2]
          SC_4: ["A", 0]
          SC_3: ["A", 1]
          SC_2: ["A", 2]
          WC_4: ["B", 0]
          WC_3: ["B", 1]
          WC_2: ["B", 2]
          EC_4: ["B", 0]
          EC_3: ["B", 1]
          EC_2: ["B", 2]
      - feature: 'count'
        user_class: 'bicycle'
        at: 'phase'
        mapping:
          0: "CYC_A"
          2: "CYC_B"
      - feature: 'count'
        user_class: 'bicycle'
        at: 'phase'
        mapping:
          0: "PED_A"
          2: "PED_B"

      tls_data:
      - feature: integer_phase
        to_variable: is_active