job:
  name: latest
  max_steps: 3000
  logging: True
  debug_tls: []

sumo:
  dir: "data"
  gui: True
  sumocfg: "run.sumocfg"

tls:
  - id: "B1"
    controller: basic_crosswalk
    constants:
      MIN_TIME: 15
    variables:
      ped_count: 0
    extract:
      - feature: count
        user_type: pedestrian
        from: phase
        mapping:
          2: "ped_count"

  - id: "C1"
    controller: basic_crosswalk
    constants:
      MIN_TIME: 15
    state_variables:
      A: [0, 0, 0]
      B: [0, 0, 0]
    control_variables:
      is_active: [0, 0, 0, 0]
    optimizer_param:
    extract:
      - feature: count
        user_type: pedestrian
        from: phase
        mapping:
          0: "A"
          2: "B"
      - feature: binary_state
        user_type: tls
        from: 
        mapping:
         0: "is_active"
